/*
 * Copyright (C) 2025 Tony Luken <tonyluken62+gerberfilereader.gmail.com>
 * 
 * This file is part of GerberFileReader.
 * 
 * GerberFileReader is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, either version 3 of 
 * the License, or (at your option) any later version.
 * 
 * GerberFileReader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with GerberFileReader. If
 * not, see <http://www.gnu.org/licenses/>.
 */

package gerberFileReader;

/**
 * A class to represent a Gerber Aperture Block
 * 
 * @see <a href="https://www.ucamco.com/files/downloads/file_en/456/gerber-layer-format-specification-revision-2024-05_en.pdf?94b45d8745c1a068fd091f095a26ddeb#page=14">
 * Section 2.4 of the Gerber Layer Format Specification</a>
 * @see <a href="https://www.ucamco.com/files/downloads/file_en/456/gerber-layer-format-specification-revision-2024-05_en.pdf?94b45d8745c1a068fd091f095a26ddeb#page=111">
 * Section 4.11 of the Gerber Layer Format Specification</a>
 */
class Block extends Aperture {
    protected AttributeDictionary apertureAttributes;
    protected int flashCount = 0;
    
    /**
     * Constructs an empty aperture block
     */
    Block() {
        
    }
    
    /**
     * Parses an opening Aperture Block command and constructs an empty aperture block with the Id
     * specified by the command. The graphical objects created during the subsequent command stream
     * (up to the matching closing Aperture Block command) should be added to the block using its 
     * put method. 
     * 
     * @param command - an opening Aperture Block command, such as: "ABD12"
     * @throws GerberLayerFormatException if the command passed does not begin with "AB" or if the 
     * aperture id is not valid
     * 
     * @see <a href="https://www.ucamco.com/files/downloads/file_en/456/gerber-layer-format-
     * specification-revision-2024-05_en.pdf?94b45d8745c1a068fd091f095a26ddeb#page=111">
     * Section 4.11 of the Gerber Specification</a>
     */
    Block(String command, AttributeDictionary attributeDictionary) 
            throws GerberLayerFormatException {
        String cmd = command.substring(0, 2);
        if (!cmd.equals("AB")) {
            throw new GerberLayerFormatException(
                    "Aperture block must be defined with an AB command but found: " + command);
        }
        type = ApertureType.BLOCK;
        int ne = Utils.numberEndIndex(command, 3);
        if (command.charAt(2) != 'D' || ne < 0) {
            throw new GerberLayerFormatException("Aperture id not valid: " + command);
        }
        id = command.substring(3, ne);
        apertureAttributes = attributeDictionary.getAllOf(AttributeType.APERTURE);
        flashCount = 0;
    }

    /**
     * Closes the block definition
     */
    public void close() {
        for (GraphicalObject go : getStream()) {
            go.getAttributes().putAll(apertureAttributes);
        }
    }
    
    /**
     * Generates one or more graphical objects by applying the aperture transformations that are 
     * currently in effect to a copy of this aperture block. The resulting graphical objects are 
     * translated so that the point corresponding to the block's origin is located at the 
     * flashPoint. The block aperture's attributes as well as any object attributes that are 
     * currently in the attribute dictionary are attached to the new graphical objects.
     * 
     * @param graphicState - the current graphic state (see section 2.6)
     * @param flashPoint - the location of the flash
     * @param attributeDictionary - the attribute dictionary
     * @return a GraphicStream containing the GraphicalObjects generated by the flash
     * @throws GerberLayerFormatException if the aperture transformation has not been set
     */
    @Override
    public GraphicsStream flash(GraphicsState graphicState, Point flashPoint, 
            AttributeDictionary attributeDictionary) throws GerberLayerFormatException {
        GraphicsStream gs = new GraphicsStream(super.flash(graphicState, flashPoint, attributeDictionary));
        for (GraphicalObject go : gs.getStream()) {
            go.getMetaData().prependBlockId(flashCount+1);
        }
        flashCount++;
        return gs;
    }

}
